In [34]:
import pandas as pd
import numpy as np
seattle_data = pd.read_csv("D:\Cloud\Anyinam\DATABASE DESIGN\Crime_Data-Washington\Seattle-Crime-Data.csv", index_col=False, delimiter=',')
seattle_data = seattle_data.replace({np.nan: None})
seattle_data.head()

,Report Number,Offense ID,Offense Start DateTime,Offense End DateTime,Report DateTime,Group A B,Crime Against Category,Offense Parent Group,Offense,Offense Code,Precinct,Sector,Beat,MCPP,100 Block Address,Longitude,Latitude
0,2020-044620,12605873663,02/05/2020 10:10:00 AM,None,02/05/2020 11:24:31 AM,A,SOCIETY,DRUG/NARCOTIC OFFENSES,Drug/Narcotic Violations,35A,W,Q,Q1,MAGNOLIA,32XX BLOCK OF 23RD AVE W,-122.385974,47.649387
1,2020-044452,12605598696,02/03/2020 08:00:00 AM,02/04/2020 08:00:00 AM,02/05/2020 10:06:28 AM,A,PROPERTY,LARCENY-THEFT,Theft of Motor Vehicle Parts or Accessories,23G,N,J,J3,ROOSEVELT/RAVENNA,63XX BLOCK OF 5TH AVE NE,-122.323399,47.675118
2,2020-044465,12605567653,02/02/2020 08:30:00 PM,02/02/2020 09:30:00 PM,02/05/2020 09:39:33 AM,A,PROPERTY,ROBBERY,Robbery,120,N,U,U3,ROOSEVELT/RAVENNA,26TH AVE NE / NE BLAKELEY ST,-122.299552,47.666384
3,2020-044225,12605174036,02/05/2020 01:17:00 AM,02/05/2020 02:21:00 AM,02/05/2020 03:30:55 AM,A,PROPERTY,DESTRUCTION/DAMAGE/VANDALISM OF PROPERTY,Destruction/Damage/Vandalism of Property,290,W,Q,Q1,MAGNOLIA,22XX BLOCK OF W RAYE ST,-122.384865,47.642927
4,2020-044076,12605081469,02/05/2020 12:51:21 AM,None,02/05/2020 12:51:31 AM,B,SOCIETY,DRIVING UNDER THE INFLUENCE,Driving Under the Influence,90D,N,B,B2,BALLARD SOUTH,NW 46TH ST / 8TH AVE NW,-122.366195,47.662193

In [31]:
seattle_data.dtypes

Report Number              object
Offense ID                  int64
Offense Start DateTime     object
Offense End DateTime       object
Report DateTime            object
Group A B                  object
Crime Against Category     object
Offense Parent Group       object
Offense                    object
Offense Code               object
Precinct                   object
Sector                     object
Beat                       object
MCPP                       object
100 Block Address          object
Longitude                 float64
Latitude                  float64
dtype: object

In [21]:
datype = {'council_district': float, 'Offense_Category': str}

Tacoma_data = pd.read_csv(r"D:\Cloud\Anyinam\DATABASE DESIGN\Crime_Data-Washington\Tacoma-Crime-Data.csv", index_col = False, delimiter= ",", dtype=datype, low_memory= False)

Tacoma_data = Tacoma_data.replace({np.nan: None})

Tacoma_data['Date_Occurred'] = pd.to_datetime(Tacoma_data['Date_Occurred'].astype(str) + ' ' + Tacoma_data['Approximate_Time'].astype(str), errors= 'coerce')

Tacoma_data.tail()

,NBD_name,NCD_name,NCD_neighborhood,Description,council_district,CaseNo,Division,Latitude,Longitude,Offense_Category,...,Address,Date_Occurred,Approximate_Time,Crimes_Against,Premise_Type,Gang_Related,Hate_Bias,TPD_District,TPD_Reporting_Block,OBJECTID
186270,None,South Tacoma,South Tacoma Neighborhood Council,Larceny Theft,5.0,2207809074,South,47.205386,-122.504209,Larceny/Theft Offenses,...,5600 S ORCHARD ST,2022-03-06 14:00:00,14:00,Property,Medical/Dental/Hospital,No/Unknown,None (No Bias),TA33,403,186271
186271,None,West End,West End Neighborhood Council,Destruction/Damage/Vandalism,1.0,2314209039,North,47.251386,-122.516209,Destruction/Damage/Vandalism,...,1000 S PEARL ST,2023-05-22 08:00:00,8:00,Property,Parking Lot,No/Unknown,None (No Bias),TA23,113,186272
186272,None,South Tacoma,South Tacoma Neighborhood Council,Larceny Theft,5.0,2134009036,South,47.193386,-122.495209,Larceny/Theft Offenses,...,6900 S STEVENS ST,2021-12-02 13:00:00,13:00,Property,Sporting Goods Store,No/Unknown,None (No Bias),TA33,405,186273
186273,None,Eastside,Eastside Neighborhood Council,Motor Vehicle Theft,4.0,1814701231,South,47.232386,-122.416209,Motor Vehicle Theft,...,3300 E K ST,2018-05-06 20:00:00,20:00,Property,Street/Right of Way,No/Unknown,None (No Bias),TA41,460,186274
186274,None,Central,Central Neighborhood Council,Larceny Theft,3.0,2312409030,North,47.237386,-122.476209,Larceny/Theft Offenses,...,2200 S CEDAR ST,2023-05-02 08:00:00,8:00,Property,Parking Lot,No/Unknown,None (No Bias),TA23,130,186275

In [22]:
Tacoma_data.dtypes

NBD_name                       object
NCD_name                       object
NCD_neighborhood               object
Description                    object
council_district               object
CaseNo                         object
Division                       object
Latitude                       object
Longitude                      object
Offense_Category               object
OffenseCode                    object
IBR_OffenseCode                object
sec_subsector                  object
Sector_Subsector               object
Sector                         object
Subsector                      object
Address                        object
Date_Occurred          datetime64[ns]
Approximate_Time               object
Crimes_Against                 object
Premise_Type                   object
Gang_Related                   object
Hate_Bias                      object
TPD_District                   object
TPD_Reporting_Block             int64
OBJECTID                        int64
dtype: object

CREATING THE MASTER FIELD DATABASE

In [2]:
import mysql.connector

# Establish a connection to the MySQL server
conn = mysql.connector.connect(
    host="localhost",  
    user="root",  
    password="An92ASA@#$%"
)

# Create a cursor object
cursor = conn.cursor()

# Create the CrimeData database
cursor.execute("CREATE DATABASE IF NOT EXISTS CrimeData")

# Select the CrimeData database
cursor.execute("USE CrimeData")

# Create the CrimeReports table
create_table_query = """
CREATE TABLE IF NOT EXISTS CrimeReports (
    IncidentID VARCHAR(50) PRIMARY KEY,
    OffenseDateTime DATETIME,
    CrimeAgainstCategory VARCHAR(100),
    Address VARCHAR(255),
    Longitude VARCHAR(255),
    Latitude VARCHAR(255),
    Offense VARCHAR(255),
    Neighbourhood TEXT
)
"""
cursor.execute(create_table_query)

# Commit the transaction
conn.commit()

# Close the cursor and connection
cursor.close()
conn.close()

print("Database and table created successfully.")

Database and table created successfully.

In [3]:
import pandas as pd
import numpy as np
import mysql.connector
from mysql.connector import Error

# Database connection
def create_connection():
    """ Create a database connection. """
    try:
        conn = mysql.connector.connect(
            host="localhost",
            user="root",
            password="An92ASA@#$%",
            database="CrimeData"
        )
        return conn
    except Error as e:
        print(f"Error: {e}")
        return None

# Define the mapping
mapping = {
    'IncidentID': {'Seattle': 'Offense ID', 'Tacoma': 'CaseNo'},
    'OffenseDateTime': {'Seattle': 'Offense Start DateTime', 'Tacoma': 'Date_Occurred'},
    'CrimeAgainstCategory': {'Seattle': 'Crime Against Category', 'Tacoma': 'Crime_Against'},
    'Address': {'Seattle': '100 Block Address', 'Tacoma': 'Address'},
    'Longitude': {'Seattle': 'Longitude', 'Tacoma': 'Longitude'},
    'Latitude': {'Seattle': 'Latitude', 'Tacoma': 'Latitude'},
    'Offense': {'Seattle': 'Offense', 'Tacoma': 'Description'},
    'Neighbourhood': {'Seattle': 'MCPP', 'Tacoma': 'NCD'}
}

# Function to load and map data in chunks
def load_and_map_data(file_path, city, chunksize=10000):
    """ Load and map data from CSV file to master format. """
    chunk_list = []
    for chunk in pd.read_csv(file_path, chunksize=chunksize, engine='python'):
        # Replace NaN values with None
        chunk = chunk.replace({np.nan: None})
        
        # Convert datetime columns
        if 'Offense Start DateTime' in chunk.columns:
            chunk['Offense Start DateTime'] = pd.to_datetime(chunk['Offense Start DateTime'], errors='coerce')
        if 'Offense End DateTime' in chunk.columns:
            chunk['Offense End DateTime'] = pd.to_datetime(chunk['Offense End DateTime'], errors='coerce')
        
        # Create a new DataFrame with the master set of fields
        master_df = pd.DataFrame(columns=mapping.keys())
        
        for master_field, city_mapping in mapping.items():
            city_field = city_mapping.get(city)
            if city_field and city_field in chunk.columns:
                master_df[master_field] = chunk[city_field]
            else:
                master_df[master_field] = None
                print(f"Warning: '{city_field}' not found in {city} file chunk")
        
        chunk_list.append(master_df)
    
    return pd.concat(chunk_list, ignore_index=True)

# Example file paths (replace with actual file paths)
seattle_file = r'D:\Cloud\Anyinam\DATABASE DESIGN\Crime_Data-Washington\Seattle-Crime-Data.csv'
tacoma_file = r'D:\Cloud\Anyinam\DATABASE DESIGN\Crime_Data-Washington\Tacoma-Crime-Data.csv'

# Load and map data for each city
print("Loading Seattle data...")
seattle_data = load_and_map_data(seattle_file, 'Seattle')
print("Loading Tacoma data...")
tacoma_data = load_and_map_data(tacoma_file, 'Tacoma')

# Combine all city data into one DataFrame
combined_data = pd.concat([seattle_data, tacoma_data], ignore_index=True)

# Insert data into MySQL
def insert_data_to_mysql(dataframe, conn):
    """ Insert data into MySQL database. """
    try:
        cursor = conn.cursor()
        insert_query = """
            INSERT INTO CrimeReports (IncidentID, OffenseDateTime, CrimeAgainstCategory, Address, Longitude, Latitude, Offense, Neighbourhood)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        """
        for _, row in dataframe.iterrows():
            cursor.execute(insert_query, (
                row['IncidentID'], row['OffenseDateTime'], row['CrimeAgainstCategory'],
                row['Address'], row['Longitude'], row['Latitude'],
                row['Offense'], row['Neighbourhood']
            ))
        conn.commit()
    except mysql.connector.Error as err:
        print(f"Error: {err}")
    finally:
        cursor.close()

# Main execution
print("Inserting data into MySQL...")
conn = create_connection()
if conn:
    insert_data_to_mysql(combined_data, conn)
    conn.close()
    print("Data loaded and inserted successfully.")
else:
    print("Failed to connect to the database.")

Loading Seattle data...
Loading Tacoma data...
Warning: 'Crime_Against' not found in Tacoma file chunk
Warning: 'NCD' not found in Tacoma file chunk
Warning: 'Crime_Against' not found in Tacoma file chunk
Warning: 'NCD' not found in Tacoma file chunk
Warning: 'Crime_Against' not found in Tacoma file chunk
Warning: 'NCD' not found in Tacoma file chunk
Warning: 'Crime_Against' not found in Tacoma file chunk
Warning: 'NCD' not found in Tacoma file chunk
Warning: 'Crime_Against' not found in Tacoma file chunk
Warning: 'NCD' not found in Tacoma file chunk
Warning: 'Crime_Against' not found in Tacoma file chunk
Warning: 'NCD' not found in Tacoma file chunk
Warning: 'Crime_Against' not found in Tacoma file chunk
Warning: 'NCD' not found in Tacoma file chunk
Warning: 'Crime_Against' not found in Tacoma file chunk
Warning: 'NCD' not found in Tacoma file chunk
Warning: 'Crime_Against' not found in Tacoma file chunk
Warning: 'NCD' not found in Tacoma file chunk
Warning: 'Crime_Against' not found in Tacoma file chunk
Warning: 'NCD' not found in Tacoma file chunk
Warning: 'Crime_Against' not found in Tacoma file chunk
Warning: 'NCD' not found in Tacoma file chunk
Warning: 'Crime_Against' not found in Tacoma file chunk
Warning: 'NCD' not found in Tacoma file chunk
Warning: 'Crime_Against' not found in Tacoma file chunk
Warning: 'NCD' not found in Tacoma file chunk
Warning: 'Crime_Against' not found in Tacoma file chunk
Warning: 'NCD' not found in Tacoma file chunk
Warning: 'Crime_Against' not found in Tacoma file chunk
Warning: 'NCD' not found in Tacoma file chunk
Warning: 'Crime_Against' not found in Tacoma file chunk
Warning: 'NCD' not found in Tacoma file chunk
Warning: 'Crime_Against' not found in Tacoma file chunk
Warning: 'NCD' not found in Tacoma file chunk
Warning: 'Crime_Against' not found in Tacoma file chunk
Warning: 'NCD' not found in Tacoma file chunk
Warning: 'Crime_Against' not found in Tacoma file chunk
Warning: 'NCD' not found in Tacoma file chunk
Inserting data into MySQL...
Error: 1292 (22007): Incorrect datetime value: '05-21-2023' for column 'OffenseDateTime' at row 1
Data loaded and inserted successfully.